version: '3'
services:
  mysql:
    image: mysql:8.0.31
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
    volumes:
      - mysql-data:/data/db

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    networks: 
      - storage-azure
    ports:
      - 10000:10000
      - 10001:10001

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2023!
    ports:
      - "27017:27017"

networks: 
  storage-azure:
    driver: bridge

volumes:
  mysql-data:
    driver: local