version: '3'
services:
  mysql:
    image: mysql:8.0.31
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
    volumes:
      - mysql-data:/data/db

volumes:
  mysql-data:
    driver: local